# Generated by Django 4.2.15 on 2024-09-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_course_instagramdata_news_prediction_trendingissue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramdata',
            name='special_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
