# Generated by Django 4.2.15 on 2024-09-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_instagramdata_special_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramdata',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
