# Generated by Django 4.2.15 on 2024-09-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_instagramdata_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingissue',
            name='first_analysis',
            field=models.BooleanField(default=False),
        ),
    ]
