# Generated by Django 4.2.15 on 2024-09-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_trendingissue_first_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendingissue',
            name='first_analysis',
        ),
        migrations.AddField(
            model_name='instagramdata',
            name='first_analysis',
            field=models.BooleanField(default=False),
        ),
    ]
