# Generated by Django 4.2.15 on 2024-09-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_factcheck_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramdata',
            name='second_analysis',
            field=models.BooleanField(default=False),
        ),
    ]
