# Generated by Django 4.2.15 on 2024-09-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_instagramdata_p_analysis_alter_prediction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramdata',
            name='p_analysis2',
            field=models.BooleanField(default=False),
        ),
    ]
