# Generated by Django 4.2.15 on 2024-09-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_finance'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramdata',
            name='f_analysis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instagramdata',
            name='f_analysis2',
            field=models.BooleanField(default=False),
        ),
    ]
