# Generated by Django 4.2.15 on 2024-09-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_instagramdata_f_analysis_instagramdata_f_analysis2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
